version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: nutriapp_mysql
    environment:
      MYSQL_ROOT_PASSWORD: Hella123.
      MYSQL_DATABASE: nutriapp
    ports:
      - "3302:3306"   
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: nutriapp_backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/nutriapp?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Hella123.
    depends_on:
      - db

volumes:
  db_data:
